### ISSUE TITLE
Make foldmethod configurable

### ISSUE THREAD

**Issue by fvictorio** [thesis/vim-solidity#10]
I'm not sure what is the best practice to do that, but *some* way of configuring it would be nice. Example, the user can do:

```
let g:solidity_fold = 'manual'
```

and the way of using it in the plugin is

```
let &l:foldmethod=get(g:, 'solidity_fold', 'syntax')
```

I can send a PR if you are ok with adding this option and with this approach.

**Comment by mhluongo** [comment]
Agreed it should be configurable! Down to peek at a couple other plugins to see what's common?

**Comment by fvictorio** [comment]
From grepping my `~/.vim/bundle`:

- `pangloss/vim-javascript` doesn't set `foldmethod`, it just gives you instructions on how to do it in the readme.
- `rust.vim` has a `g:rust_fold` variable, where 0 is no folding, and 1 are 2 set the method to syntax with different levels

The rest of the plugins only change `foldmethod` temporarily or for plugin-specific buffers.

I think both approaches make sense, but personally I prefer the `vim-javascript` one of not doing anything and assuming this is done by the user.

**Comment by mhluongo** [comment]
@Philogy going to take this approach of not stomping on `foldmethod`. Thanks @fvictorio!
